name: torn_pda
description: Torn City personal assistant

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  rxdart: ^0.25.0
  flutter_local_notifications: ^4.0.0
  url_launcher: ^5.7.10
  intl: ^0.16.1
  android_intent: ^0.3.7+7
  shared_preferences: ^0.5.12+4
  flutter_slidable: ^0.5.7
  provider: ^4.3.3
  percent_indicator: ^2.1.9+1
  webview_flutter: ^1.0.7
  share: ^0.6.5+4
  html: ^0.14.0+4
  sliding_up_panel: ^1.0.2
  expandable: ^4.1.4
  timeline_tile: ^1.0.0
  animations: ^1.1.2
  bot_toast: ^3.0.5
  material_design_icons_flutter: ^4.0.5855
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_analytics: ^6.3.0
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  firebase_crashlytics: ^0.2.4
  easy_rich_text: ^0.5.3
  wakelock: ^0.2.1+1
  audioplayers: 0.17.0
  vibration: ^1.7.3
  bubble_showcase: ^0.2.0+4
  speech_bubble: ^0.0.7
  cupertino_icons: ^1.0.2
  quick_actions: ^0.4.0+10
  timezone: ^0.6.1
  cookie_jar: ^1.0.1
  fl_chart: ^0.12.2
  dotted_border: ^1.0.7
  flutter_colorpicker: ^0.3.5
  device_info: ^1.0.0
  pull_to_refresh: ^1.6.3
  flutter_inappwebview: ^5.0.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/icons/torn_pda.png"
  image_path_ios: "images/icons/torn_pda_ios.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/awards/
    - images/awards/honors/
    - images/awards/medals/
    - images/awards/categories/
    - images/flags/stock/
    - images/flags/travel/
    - images/icons/
    - images/icons/cooldowns/
    - images/icons/map/
    - images/icons/inventory/
    - images/icons/home/
    - images/torn_items/small/
    - images/npcs/
    - sounds/alerts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
